# Generated by Django 5.1.4 on 2024-12-24 14:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dl_number', models.CharField(blank=True, help_text='Driving license number', max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="DL number must follow the pattern 'DL-1420110012345' or 'DL14 20110012345'.", regex='^DL-\\d{2}\\d{11}$|^DL\\d{2}\\s\\d{11}$')])),
                ('dl_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
